name: CI Mobile

on:
  push:
    branches: ['**']  # Se ejecuta en todas las ramas
  pull_request:
    branches: ['**']  # Se ejecuta en todas las ramas

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'        # o la versi√≥n que uses
          cache: 'npm'              # o 'yarn'

      - name: Install dependencies
        run: |
          npm install
          # o: yarn install --frozen-lockfile

      - name: Run unit tests
        run: npm test -- --ci --watchAll=false --passWithNoTests

  trigger-cd:
    needs: test
    runs-on: ubuntu-latest
    if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/feature/auth' || contains(github.ref, 'refs/heads/feature/auth/'))
    steps:
      - name: Trigger CD Android
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'cd-android.yml',
              ref: context.ref
            });
      
      - name: Trigger CD iOS
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'cd-ios.yml',
              ref: context.ref
            });
